In [1]:
import pandas as pd
import calendar

In [16]:
energyUnit = "kWh"
hoursinaday = 24

costColPostfix = "Cost"

optimization1 = "Prev"
cost1ColName = "{:}{:}".format(optimization1, costColPostfix)
util1ColName = "{:}{:}".format(cost1ColName, energyUnit)

optimization2 = "Prop"
cost2ColName = "{:}{:}".format(optimization2, costColPostfix)
util2ColName = "{:}{:}".format(cost2ColName, energyUnit)

savedColName = "Energy Cost Saved"

In [17]:
mydata = pd.read_csv("/home/xsif/kongju/code-sehysif/PSO_Asif/data.txt")
mydata["timestamp"] = pd.to_datetime(mydata["timestamp"])

## Months

In [35]:
months_costs_df = pd.read_csv("results/Months/Months-Costs/Months-Costs.txt", sep = ",")
months_costs_df.index += 1
months_costs_df.fillna(0, inplace = True)
months_costs_df = months_costs_df.astype({
    "Months":"float",
    "Simulations":"float",
    cost1ColName:"float",
    cost2ColName:"float",
})
months_costs_df[util1ColName] = round((months_costs_df[cost1ColName]/months_costs_df["Months"])/hoursinaday, 2)
months_costs_df[util2ColName] = round((months_costs_df[cost2ColName]/months_costs_df["Months"])/hoursinaday, 2)
months_costs_df[savedColName] = months_costs_df[cost1ColName]-months_costs_df[cost2ColName]

In [36]:
months_costs_df

,Start,End,Months,Simulations,PrevCost,PropCost,PrevCostkWh,PropCostkWh,Energy Cost Saved
1,2014 May,2014 May,1.0,744.0,1926.83,522.69,80.28,21.78,1404.14
2,2014 May,2014 June,2.0,1464.0,3790.77,1028.71,78.97,21.43,2762.06
3,2014 May,2014 July,3.0,2208.0,5647.17,1548.45,78.43,21.51,4098.72
4,2014 May,2014 August,4.0,2952.0,7549.21,2070.26,78.64,21.57,5478.95
5,2014 May,2014 September,5.0,3672.0,9464.63,2578.80,78.87,21.49,6885.83
6,2014 May,2014 October,6.0,4416.0,11474.70,3105.31,79.69,21.56,8369.39
7,2014 May,2014 November,7.0,5136.0,13476.65,3617.95,80.22,21.54,9858.70
8,2014 May,2014 December,8.0,5880.0,15574.62,4148.77,81.12,21.61,11425.85
9,2014 May,2015 January,9.0,6624.0,17669.89,4679.95,81.81,21.67,12989.94
10,2014 May,2015 February,10.0,7296.0,19503.27,5156.34,81.26,21.48,14346.93
11,2014 May,2015 March,11.0,8040.0,21449.89,5679.94,81.25,21.51,15769.95
12,2014 May,2015 April,12.0,8760.0,23456.78,6183.92,81.45,21.47,17272.86

In [37]:
months_costs_avg1 = round(months_costs_df[util1ColName].sum()/len(months_costs_df), 2)
months_costs_avg2 = round(months_costs_df[util2ColName].sum()/len(months_costs_df), 2)
print ("The energy used at the rate of {:} {:} when using {:}. optimization approach".format(months_costs_avg1, energyUnit, optimization1))
print ("The energy used at the rate of {:} {:} when using {:}. optimization approach".format(months_costs_avg2, energyUnit, optimization2))

The energy used at the rate of 80.17 kWh when using Prev. optimization approach
The energy used at the rate of 21.55 kWh when using Prop. optimization approach

## Monthwise

In [38]:
# mydata = pd.read_csv("/home/xsif/kongju/code-sehysif/PSO_Asif/data.txt")
# mydata["timestamp"] = pd.to_datetime(mydata["timestamp"])
# year = 2015
# month = 5
# mydata[
#     (mydata["timestamp"].dt.year == year)
#     & (mydata["timestamp"].dt.month == month)
# ].to_csv("results/Monthwise/Monthwise-Data/data-{:}-{:}.txt".format(year, month), index = False)

In [70]:
monthwise_costs_df = pd.read_csv("results/Monthwise/Monthwise-Costs/Monthwise-Costs.txt", sep = ",")
monthwise_costs_df.index += 1
monthwise_costs_df.fillna(0, inplace = True)
monthwise_costs_df = monthwise_costs_df.astype({
    cost1ColName:"float",
    cost2ColName:"float",
})
monthwise_costs_df[util1ColName] = round((monthwise_costs_df[cost1ColName]/1)/hoursinaday, 2)
monthwise_costs_df[util2ColName] = round((monthwise_costs_df[cost2ColName]/1)/hoursinaday, 2)
monthwise_costs_df[savedColName] = monthwise_costs_df[cost1ColName]-monthwise_costs_df[cost2ColName]

monthwise_costs_df_row = {
    monthwise_costs_df.columns[0]: "2014-2015",
    monthwise_costs_df.columns[1]: "All",
    monthwise_costs_df.columns[2]: 0,
    monthwise_costs_df.columns[3]: monthwise_costs_df[cost1ColName].sum(),
    monthwise_costs_df.columns[4]: monthwise_costs_df[cost2ColName].sum(),
    monthwise_costs_df.columns[5]: monthwise_costs_df[util1ColName].sum(),
    monthwise_costs_df.columns[6]: monthwise_costs_df[util2ColName].sum(),
    monthwise_costs_df.columns[7]: monthwise_costs_df[savedColName].sum(),
}
monthwise_costs_df = monthwise_costs_df.append(monthwise_costs_df_row, ignore_index = True)

/tmp/ipykernel_210500/1501461167.py:22: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  monthwise_costs_df = monthwise_costs_df.append(monthwise_costs_df_row, ignore_index = True)

In [71]:
monthwise_costs_df

,Year,Month,Simulations,PrevCost,PropCost,PrevCostkWh,PropCostkWh,Energy Cost Saved
0,2014,May,744,1926.81,522.70,80.28,21.78,1404.11
1,2014,June,720,1863.27,506.04,77.64,21.08,1357.23
2,2014,July,744,1857.15,519.77,77.38,21.66,1337.38
3,2014,August,744,1898.68,521.85,79.11,21.74,1376.83
4,2014,September,720,1916.56,508.49,79.86,21.19,1408.07
5,2014,October,744,2007.36,526.55,83.64,21.94,1480.81
6,2014,November,720,2002.67,512.57,83.44,21.36,1490.10
7,2014,December,744,2096.59,531.00,87.36,22.12,1565.59
8,2015,January,744,2097.26,531.04,87.39,22.13,1566.22
9,2015,February,672,1830.15,476.41,76.26,19.85,1353.74
10,2015,March,744,1949.24,523.65,81.22,21.82,1425.59
11,2015,April,720,1829.43,503.90,76.23,21.00,1325.53
12,2014-2015,All,0,23275.17,6183.97,969.81,257.67,17091.20

In [72]:
monthwise_costs_avg1 = round(monthwise_costs_df[util1ColName].sum()/len(monthwise_costs_df), 2)
monthwise_costs_avg2 = round(monthwise_costs_df[util2ColName].sum()/len(monthwise_costs_df), 2)
print ("The energy used at the rate of {:} {:} when using {:}. optimization approach".format(monthwise_costs_avg1, energyUnit, optimization1))
print ("The energy used at the rate of {:} {:} when using {:}. optimization approach".format(monthwise_costs_avg2, energyUnit, optimization2))

The energy used at the rate of 149.2 kWh when using Prev. optimization approach
The energy used at the rate of 39.64 kWh when using Prop. optimization approach

## Seasonwise

In [73]:
# seasons = {
#     "spring-2014":{"start":{"year":2014, "month":3}, "end":{"year":2014, "month":5}},
#     "summer-2014":{"start":{"year":2014, "month":6}, "end":{"year":2014, "month":8}},
#     "autumn-2014":{"start":{"year":2014, "month":9}, "end":{"year":2014, "month":11}},
#     "winter-2014-2015":{"start":{"year":2014, "month":12}, "end":{"year":2015, "month":2}},
#     "spring-2015":{"start":{"year":2015, "month":3}, "end":{"year":2015, "month":5}},
# }
# season_name = "spring-2015"
# current_season = seasons[season_name]
# yearstart, yearend = current_season["start"]["year"], current_season["end"]["year"]
# monthstart, monthend = current_season["start"]["month"], current_season["end"]["month"]
# mydata[
#     (mydata["timestamp"].dt.year >= yearstart)
#     & (mydata["timestamp"].dt.year <= yearend)
#     & (mydata["timestamp"].dt.month >= monthstart)
#     & (mydata["timestamp"].dt.month <= monthend)
# ].to_csv("results/Seasonwise/Seasonwise-Data/data-{:}-{:}-{:}.txt".format(
#     season_name, calendar.month_abbr[monthstart], calendar.month_abbr[monthend]
# ), index = False)

In [74]:
# season_name = "winter-2014-2015"
# current_season = seasons[season_name]
# yearstart, yearend = current_season["start"]["year"], current_season["end"]["year"]
# monthstart, monthend = current_season["start"]["month"], current_season["end"]["month"]
# mydata[
#     ((mydata["timestamp"].dt.year == yearstart)
#     & (mydata["timestamp"].dt.month >= monthstart))
#     | ((mydata["timestamp"].dt.year == yearend)
#     & (mydata["timestamp"].dt.month <= monthend))
# ].to_csv("results/Seasonwise/Seasonwise-Data/data-{:}-{:}-{:}.txt".format(
#     season_name, calendar.month_abbr[monthstart], calendar.month_abbr[monthend]
# ), index = False)

In [82]:
seasonwise_costs_df = pd.read_csv("results/Seasonwise/Seasonwise-Costs/Seasonwise-Costs.txt", sep = ",")
seasonwise_costs_df.index += 1
seasonwise_costs_df.fillna(0, inplace = True)
seasonwise_costs_df = seasonwise_costs_df.astype({
    cost1ColName:"float",
    cost2ColName:"float",
})
seasonwise_costs_df[util1ColName] = round((seasonwise_costs_df[cost1ColName]/seasonwise_costs_df["Months"])/hoursinaday, 2)
seasonwise_costs_df[util2ColName] = round((seasonwise_costs_df[cost2ColName]/seasonwise_costs_df["Months"])/hoursinaday, 2)

seasonwise_costs_df[savedColName] = seasonwise_costs_df[cost1ColName]-seasonwise_costs_df[cost2ColName]

seasonwise_costs_df_row = {
    seasonwise_costs_df.columns[0]: "All seasons",
    seasonwise_costs_df.columns[1]: seasonwise_costs_df[seasonwise_costs_df.columns[1]].sum(),
    seasonwise_costs_df.columns[2]: 0,
    seasonwise_costs_df.columns[3]: seasonwise_costs_df[cost1ColName].sum(),
    seasonwise_costs_df.columns[4]: seasonwise_costs_df[cost2ColName].sum(),
    seasonwise_costs_df.columns[5]: seasonwise_costs_df[util1ColName].sum(),
    seasonwise_costs_df.columns[6]: seasonwise_costs_df[util2ColName].sum(),
    seasonwise_costs_df.columns[7]: seasonwise_costs_df[savedColName].sum(),
}
seasonwise_costs_df = seasonwise_costs_df.append(seasonwise_costs_df_row, ignore_index = True)

/tmp/ipykernel_210500/2985662777.py:23: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  seasonwise_costs_df = seasonwise_costs_df.append(seasonwise_costs_df_row, ignore_index = True)

In [83]:
seasonwise_costs_df

,Season,Months,Simulations,PrevCost,PropCost,PrevCostkWh,PropCostkWh,Energy Cost Saved
0,Spring-2014 (May),1,744,1927.03,522.70,80.29,21.78,1404.33
1,Summer-2014 (Jun-Aug),3,2208,5621.96,1547.59,78.08,21.49,4074.37
2,Autumn-2014 (Sept-Nov),3,2184,5927.82,1547.62,82.33,21.49,4380.20
3,Winter-2014-15 (Dec-Feb),3,2160,6023.88,1538.46,83.66,21.37,4485.42
4,Spring-2015 (Mar-Apr),2,1464,3778.16,1027.53,78.71,21.41,2750.63
5,All seasons,12,0,23278.85,6183.90,403.07,107.54,17094.95

In [84]:
seasonwise_costs_avg1 = round(seasonwise_costs_df[util1ColName].sum()/len(seasonwise_costs_df), 2)
seasonwise_costs_avg2 = round(seasonwise_costs_df[util2ColName].sum()/len(seasonwise_costs_df), 2)
print ("The energy used at the rate of {:} {:} when using {:}. optimization approach".format(seasonwise_costs_avg1, energyUnit, optimization1))
print ("The energy used at the rate of {:} {:} when using {:}. optimization approach".format(seasonwise_costs_avg2, energyUnit, optimization2))

The energy used at the rate of 134.36 kWh when using Prev. optimization approach
The energy used at the rate of 35.85 kWh when using Prop. optimization approach